-- Avas Thaa — 0005: cart & orders
-- One open cart per customer per business (enforced below), so switching
-- restaurants naturally starts a fresh cart instead of mixing vendors.

create table carts (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references profiles(id) on delete cascade,
  business_id uuid not null references businesses(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_carts_updated_at before update on carts
  for each row execute function set_updated_at();

-- A profile may have several *closed* historical carts but only one open
-- cart per business at a time; enforced via a partial unique index.
create unique index uq_open_cart_per_business
  on carts (profile_id, business_id);

create table cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references carts(id) on delete cascade,
  menu_item_id uuid references menu_items(id),
  product_id uuid references products(id),
  quantity int not null default 1 check (quantity > 0),
  selected_options jsonb not null default '[]', -- [{option_id, name, price_delta}]
  special_instructions text,
  unit_price numeric(10, 2) not null, -- snapshot at add-to-cart time
  created_at timestamptz not null default now(),
  check (
    (menu_item_id is not null and product_id is null) or
    (menu_item_id is null and product_id is not null)
  )
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique, -- human-readable, generated by trigger below
  customer_id uuid not null references profiles(id),
  business_id uuid not null references businesses(id),
  status order_status not null default 'pending',
  delivery_method delivery_method not null default 'door_delivery',
  delivery_address_id uuid references addresses(id),
  scheduled_for timestamptz, -- null unless delivery_method = 'scheduled'
  subtotal numeric(10, 2) not null default 0,
  delivery_fee numeric(10, 2) not null default 0,
  platform_fee numeric(10, 2) not null default 0,
  discount_amount numeric(10, 2) not null default 0,
  total_amount numeric(10, 2) not null default 0,
  coupon_id uuid, -- FK added in 0007 once coupons exists
  payment_method payment_method not null default 'cash',
  payment_status payment_status not null default 'pending',
  special_instructions text,
  contact_phone text not null,
  rejection_reason text,
  cancelled_reason text,
  cancelled_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_orders_updated_at before update on orders
  for each row execute function set_updated_at();

create sequence order_number_seq;
create or replace function generate_order_number()
returns trigger
language plpgsql
as $$
begin
  new.order_number := 'AT-' || to_char(now(), 'YYMMDD') || '-' ||
    lpad(nextval('order_number_seq')::text, 5, '0');
  return new;
end;
$$;
create trigger trg_orders_order_number before insert on orders
  for each row execute function generate_order_number();

create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  menu_item_id uuid references menu_items(id),
  product_id uuid references products(id),
  item_name text not null, -- snapshot: survives menu/product edits or deletion
  quantity int not null check (quantity > 0),
  unit_price numeric(10, 2) not null,
  selected_options jsonb not null default '[]',
  options_total numeric(10, 2) not null default 0,
  line_total numeric(10, 2) not null,
  special_instructions text
);

-- Full audit trail backing the customer-facing status timeline.
create table order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  status order_status not null,
  changed_by uuid references profiles(id),
  note text,
  created_at timestamptz not null default now()
);

create or replace function log_order_status_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if (tg_op = 'INSERT') or (new.status is distinct from old.status) then
    insert into order_status_history (order_id, status, changed_by)
    values (new.id, new.status, auth.uid());
  end if;
  return new;
end;
$$;
create trigger trg_orders_status_history
  after insert or update of status on orders
  for each row execute function log_order_status_change();
